// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RouteTracker.Api.Data;

#nullable disable

namespace RouteTracker.Api.Data.Migrations
{
    [DbContext(typeof(RouteTrackerContext))]
    partial class RouteTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("RouteTracker.Api.Models.Boulder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("SetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Setter")
                        .HasColumnType("TEXT");

                    b.Property<int>("VermGradeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("VermGradeId");

                    b.ToTable("Boulders");
                });

            modelBuilder.Entity("RouteTracker.Api.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("RouteTracker.Api.Models.DecimalGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GradeValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DecimalGrades");
                });

            modelBuilder.Entity("RouteTracker.Api.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecimalGradeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("SetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Setter")
                        .HasColumnType("TEXT");

                    b.Property<int>("SetterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WallNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("DecimalGradeId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("RouteTracker.Api.Models.Setter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Setters");
                });

            modelBuilder.Entity("RouteTracker.Api.Models.VermGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GradeValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VermGrades");
                });

            modelBuilder.Entity("RouteTracker.Api.Models.Boulder", b =>
                {
                    b.HasOne("RouteTracker.Api.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RouteTracker.Api.Models.VermGrade", "VermGrade")
                        .WithMany()
                        .HasForeignKey("VermGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("VermGrade");
                });

            modelBuilder.Entity("RouteTracker.Api.Models.Route", b =>
                {
                    b.HasOne("RouteTracker.Api.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RouteTracker.Api.Models.DecimalGrade", "DecimalGrade")
                        .WithMany()
                        .HasForeignKey("DecimalGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("DecimalGrade");
                });
#pragma warning restore 612, 618
        }
    }
}
